spring:
  datasource:
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB}
    username: ${POSTGRES_USER}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

#    show-sql: true
#  flyway:
#    baseline-on-migrate: true
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB}
